import type { Language } from '@/i18n/types'
import type { Skill } from '@/types/content'

const skillsByLanguage: Record<Language, Skill[]> = {
  es: [
    { id: 'react', title: 'React', group: 'frontend' },
    { id: 'typescript', title: 'TypeScript', group: 'frontend' },
    { id: 'javascript', title: 'JavaScript', group: 'frontend' },
    { id: 'flutter', title: 'Flutter', group: 'frontend' },
    { id: 'dart', title: 'Dart', group: 'frontend' },
    { id: 'html5', title: 'HTML5', group: 'frontend' },
    { id: 'scss', title: 'SASS/SCSS', group: 'frontend' },
    { id: 'vue', title: 'Vue', group: 'frontend' },
    { id: 'responsive', title: 'Diseno Responsive', group: 'frontend' },
    { id: 'performance-optimization', title: 'Optimizacion de Rendimiento', group: 'frontend' },
    { id: 'pdfjs', title: 'PDF.js', group: 'frontend' },
    { id: 'nodejs', title: 'Node.js', group: 'backendData' },
    { id: 'supabase', title: 'Supabase', group: 'backendData' },
    { id: 'golang', title: 'Golang', group: 'backendData' },
    { id: 'pyspark', title: 'PySpark', group: 'backendData' },
    { id: 'rest-apis', title: 'APIs REST', group: 'backendData' },
    { id: 'postgresql', title: 'PostgreSQL', group: 'backendData' },
    { id: 'authentication-security', title: 'Autenticacion y Seguridad', group: 'backendData' },
    { id: 'git', title: 'Git', group: 'toolsDevops' },
    { id: 'github', title: 'GitHub / GitLab', group: 'toolsDevops' },
    { id: 'docker', title: 'Docker', group: 'toolsDevops' },
    { id: 'cicd', title: 'CI/CD', group: 'toolsDevops' },
    { id: 'vite', title: 'Vite', group: 'toolsDevops' },
    { id: 'firebase', title: 'Firebase', group: 'toolsDevops' },
    { id: 'agile-scrum', title: 'Agile / Scrum', group: 'toolsDevops' },
    { id: 'clean-code', title: 'Clean Code', group: 'toolsDevops' },
  ],
  en: [
    { id: 'react', title: 'React', group: 'frontend' },
    { id: 'typescript', title: 'TypeScript', group: 'frontend' },
    { id: 'javascript', title: 'JavaScript', group: 'frontend' },
    { id: 'flutter', title: 'Flutter', group: 'frontend' },
    { id: 'dart', title: 'Dart', group: 'frontend' },
    { id: 'html5', title: 'HTML5', group: 'frontend' },
    { id: 'scss', title: 'SASS/SCSS', group: 'frontend' },
    { id: 'vue', title: 'Vue', group: 'frontend' },
    { id: 'responsive', title: 'Responsive Design', group: 'frontend' },
    { id: 'performance-optimization', title: 'Performance Optimization', group: 'frontend' },
    { id: 'pdfjs', title: 'PDF.js', group: 'frontend' },
    { id: 'nodejs', title: 'Node.js', group: 'backendData' },
    { id: 'supabase', title: 'Supabase', group: 'backendData' },
    { id: 'golang', title: 'Golang', group: 'backendData' },
    { id: 'pyspark', title: 'PySpark', group: 'backendData' },
    { id: 'rest-apis', title: 'REST APIs', group: 'backendData' },
    { id: 'postgresql', title: 'PostgreSQL', group: 'backendData' },
    { id: 'authentication-security', title: 'Authentication and Security', group: 'backendData' },
    { id: 'git', title: 'Git', group: 'toolsDevops' },
    { id: 'github', title: 'GitHub / GitLab', group: 'toolsDevops' },
    { id: 'docker', title: 'Docker', group: 'toolsDevops' },
    { id: 'cicd', title: 'CI/CD', group: 'toolsDevops' },
    { id: 'vite', title: 'Vite', group: 'toolsDevops' },
    { id: 'firebase', title: 'Firebase', group: 'toolsDevops' },
    { id: 'agile-scrum', title: 'Agile / Scrum', group: 'toolsDevops' },
    { id: 'clean-code', title: 'Clean Code', group: 'toolsDevops' },
  ],
}

export const getSkills = (language: Language): Skill[] => skillsByLanguage[language]